In [1]:
path1 = 'ham_data.txt'  # 正常邮件存放地址
path2 = 'spam_data.txt'  # 垃圾邮件地址

In [2]:
h = open(path1, encoding='utf-8')
h

<_io.TextIOWrapper name='ham_data.txt' mode='r' encoding='utf-8'>

In [3]:
h_data = h.readlines()

In [4]:
h_data[0:3]  # 显示前3封正常邮件

['讲的是孔子后人的故事。一个老领导回到家乡，跟儿子感情不和，跟贪财的孙子孔为本和睦。 老领导的弟弟魏宗万是赶马车的。 有个洋妞大概是考察民俗的，在他们家过年。 孔为本总想出国，被爷爷教育了。 最后，一家人基本和解。 顺便问另一类电影，北京青年电影制片厂的。中越战背景。一军人被介绍了一个对象，去相亲。女方是军队医院的护士，犹豫不决，总是在回忆战场上负伤的男友，好像还没死。最后 男方表示理解，归队了。\n',
 '不至于吧，离开这个破公司就没有课题可以做了？ 谢谢大家的关心，她昨天晚上睡的很好。MM她自己已经想好了。见机行事吧，拿到相关的能出来做论文的材料，就马上辞职。 唉！看看吧，说不定还要各为XDJM帮出出找工作的主意呢。MM学通信的，哈尔滨工程大学的研究生，不想在哈碌碌无为的做设计，因此才出来的。先谢谢了啊。！！！ 本人语文不好，没加标点。辛苦那些看不懂的XDJM么了。\n',
 '生一个玩玩，不好玩了就送人 第一，你要知道，你们恋爱前，你爹妈对她是毫无意义的。没道理你爹妈就要求她生孩子，她就得听话。换句话说，你岳父母要未来孩子跟妈姓，你做的到吗？夫妻是平等的。如果你没办法答应岳父母，她干吗答应你爹妈呢？ 第二，有了孩子你养不养的起？不是说想生就生，图你爹妈一个高兴，如果没有房子，没有充足的财力，生孩子只会带给你们更多的困难，生小孩容易，养小孩难啊。\n']

In [5]:
s = open(path2, encoding='utf-8')
s_data = s.readlines()

In [6]:
s_data[0:3]  # 显示前3个封垃

['有情之人，天天是节。一句寒暖，一线相喧；一句叮咛，一笺相传；一份相思， 一心相盼；一份爱意，一生相恋。 搜寻201:::http://201.855.com 在此祝大家七夕情人快乐! 搜寻201友情提示::: 2005年七夕情人节：8月11日――别忘了给她（他）送祝福哦！\n',
 '我司是一家实业贸易定税企业；有余额票向外开 费用相对较低，此操作方式可以为贵公司（工厂） 节约部分税金。 公司本着互利互惠的原则,真诚期待你的来电!!! 联系: 王生   TEL: --13528886061\n',
 '本公司有部分普通发票（商品销售发票）增值税发票及海关代征增值税专用缴款书及其它服务行业发票, 公路、内河运输发票。可以以低税率为贵公司代开，本公司具有内、外贸生意实力，保证我司开具的票据的真实性。 希望可以合作!共同发展!敬侯您的来电洽谈、咨询！ 联系人：李先生      联系电话：13632588281 如有打扰望谅解，祝商琪。\n']

In [7]:
import numpy as np

h_labels = np.ones(len(h_data)).tolist()  # 生成一个len(h_data)长的的一维全1列表
h_labels[0:10]  # 我们显示前10个数据

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

In [8]:
s_labels = np.zeros(len(s_data)).tolist()
s_labels[0:10]  # 我们显示前10个数据

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [9]:
datas = h_data + s_data  # 将正常样本和垃圾样本整合到datas当中
labels = h_labels + s_labels

In [10]:
from sklearn.model_selection import train_test_split

train_d, test_d, train_y, test_y = train_test_split(
    datas, labels, test_size=0.25, random_state=5)

In [11]:
train_y[0:30]

[0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0]

In [12]:
import jieba


def tokenize_words(corpus):
    tokenized_words = jieba.cut(corpus)
    tokenized_words = [token.strip() for token in tokenized_words]
    return tokenized_words

In [17]:
string = '我的名字是刘国柄'
b = tokenize_words(string)
b

['我', '的', '名字', '是', '刘', '国柄']

In [15]:
def remove_stopwords(corpus):  # 函数输入为样本集
    sw = open('stop_word.txt', encoding='utf-8')  # stopwords 停词表
    sw_set = set(l.strip() for l in sw)
    tokenized_data = tokenize_words(corpus)
    filtered_data = [data for data in tokenized_data if data not in sw_set]
    filtered_datas = ' '.join(filtered_data)
    return filtered_datas  # 返回去停用词之后的 datas

In [16]:
remove_stopwords("我的名字是刘国柄")

'名字 刘 国柄'

In [18]:
from tqdm.notebook import tqdm


def preprocessing_datas(datas):
    preprocessed_datas = []
    # 对 datas 当中的每一个 data 进行去停用词操作
    # 并添加到上面刚刚建立的 preprocessed_datas 当中
    for data in tqdm(datas):
        data = remove_stopwords(data)
        preprocessed_datas.append(data)

    return preprocessed_datas  # 返回去停用词之后的新的样本集

In [19]:
pred_train_d = preprocessing_datas(train_d)
pred_train_d[0]

'敬 用户 你好 1798 国际 贸易网 http www.1798 cn 全球排名 1.2 万名 商业 门户网站 现 免费 开放 发布 供求信息 人才 招聘 互联网 址 注册 请 点击 注册 http www.1798 cn index asp'

In [20]:
pred_test_d = preprocessing_datas(test_d)
pred_test_d[0]

'全球 中文 创业 门户 令 全球 震惊 成功 秘密 www zhaozhao360 com 上班族 另类 火爆 发财 法 兼职 创业 好了吗 美女 老板 掘 第一桶金 19 岁 小女子 年 净赚 30 万 内衣 试穿 妹 试成 白金 丽 中国 新 九大 暴利行业 比尔 ・ 盖茨 花钱 赚到 500 万 一条 狗 工资 400 40000'

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    min_df=1, norm='l2', smooth_idf=True, use_idf=True, ngram_range=(1, 1))

In [22]:
tfidf_train_features = vectorizer.fit_transform(pred_train_d)
tfidf_train_features

<7500x28336 sparse matrix of type '<class 'numpy.float64'>'
	with 199263 stored elements in Compressed Sparse Row format>

In [23]:
tfidf_train_features.toarray()[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [24]:
tfidf_test_features = vectorizer.transform(pred_test_d)
tfidf_test_features

<2501x28336 sparse matrix of type '<class 'numpy.float64'>'
	with 61045 stored elements in Compressed Sparse Row format>

In [25]:
from sklearn.linear_model import SGDClassifier

svm = SGDClassifier(loss='hinge')

In [26]:
svm.fit(tfidf_train_features, train_y)

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [27]:
predictions = svm.predict(tfidf_test_features)
predictions

array([0., 1., 1., ..., 0., 1., 0.])

In [28]:
from sklearn import metrics

accuracy_score = np.round(metrics.accuracy_score(test_y, predictions), 2)
accuracy_score

0.99

In [29]:
metrics.confusion_matrix(test_y, predictions)

array([[1212,   21],
       [   6, 1262]], dtype=int64)

In [32]:
print(metrics.classification_report(test_y, predictions))

              precision    recall  f1-score   support

         0.0       1.00      0.98      0.99      1233
         1.0       0.98      1.00      0.99      1268

    accuracy                           0.99      2501
   macro avg       0.99      0.99      0.99      2501
weighted avg       0.99      0.99      0.99      2501



In [34]:
import random

In [38]:
n = random.randint(0,2500)
print('邮件类型：', test_y[n])
print('预测邮件类型：', predictions[n])
print('文本：', test_d[n])

邮件类型： 1.0
预测邮件类型： 1.0
文本： 算了 曾经非常喜欢她，无论什么方面都不错的一个mm（我的眼中），可是表白之后从她的反应来看觉得没戏，就狠心放弃了，希望时间来冲淡一切，删掉号码，不见面不打电话，经过一段时间忘得差不多了，还想跟另一个女孩接触接触呢。 可是今天由于某种原因，又见面了（还有其他朋友），一个多月的努力白费了，又燃起了爱的火焰，可是我知道继续追的话希望也不大。又要痛苦几天了。 兴趣上没有足够切合点，肯定没什么希望的。郁闷

